name: Build and Deploy

on:
  push:
    branches:
      - master # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # You can specify your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build # Adjust this if your build command is different

      - name: Deploy to GitHub Pages
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git remote add gh-pages https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git subtree push --prefix build gh-pages master
